config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 5, maximum: 5000 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum:105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end            

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end

  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
     if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit

  end

  def show
    
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:success] = "Article was successfully deleted"
    redirect_to articles_path
  end

private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [] )
  end

  def require_same_user
    if current_user != @article.user && !current_user.is_admin
      flash[:danger] = "You can only edit or delete your own article."  
      redirect_to root_path
    end  
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, except: [:index, :new, :create]
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "You have successfully created a new category"
      redirect_to @category
    else
      render 'new'
    end
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
    
  end
  
  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end    
  end  

  def destroy    
    @category.destroy
    flash[:success] = "You have successfully deleted a category."
    redirect_to categories_path
  end
    
  private
  def set_category
    @category = Category.find(params[:id])
  end
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.is_admin?)
      flash[:danger] = "Only an admin can perform that action."
      redirect_to categories_path
    end
  end    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit    
    
  end

  def update    
    if @user.update(user_params)
      flash[:success] = "You have successfully updated your account"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted."
    redirect_to users_path
  end  
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  def set_user
    @user = User.find(params[:id])  
  end
  def require_same_user
    if current_user != @user && !current_user.is_admin?
      flash[:danger] = "You can only edit your own account."
      redirect_to root_path
    end
  end
  def require_admin
    if logged_in? && !current_user.is_admin?
      flash[:danger] = "Only an admin can perform that action."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded-circle', size: '150')
  end
end

app/views/articles/_articles.html.erb
 
 <% obj.each do |article| %>
      <div class="article_container container p-3">
        <div class="row m-2">
          <div class="col center">
            <%= link_to article.title, article_path(article) %>
          </div>            
        </div>
        <div class="row m-2">
          <div class="col">
            Description:  <%= article.description.truncate(100, separator: ' ') %> <br>
            <div class="article-meta-details">            
              <small>Created by: <%= article.user.username %>,  
                <%= time_ago_in_words(article.created_at) %> ago.
                    Last updated: <%= time_ago_in_words(article.updated_at) %> ago.</small>
            </div>      
          </div>            
        </div>
        <div class="row ml-2">
          <div class="col">
            <% if article.categories %>
              <p class="category_listing">Categories: <%= render article.categories %></p>
            <% end %>
          </div>  
        </div>
        <div>
          <% if logged_in? && (current_user == article.user || current_user.is_admin?) %>
            <div class="row ml-2">    
              <div class="col">             
                <%= link_to 'Edit article', edit_article_path(article), class: "btn btn-outline-primary btn-sm mr-2" %>
                <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger btn-sm m-2" %>    
              </div>                         
            </div>
          <% end %>   
        </div>
      </div>
    <% end %>  

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
      
<%= form_for @article do |f| %>
  <div class="container p-3">
    <div class="form-group row m-2">
      <%= f.label :title, class: "col-md-2 col-form-label" %>
      <div class="col-md-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row m-2">
      <%= f.label :description, class: "col-md-2 col-form-label", value: "Article" %>
      <div class="col-md-10">
        <%= f.text_area :description,  class: "form-control" %>
      </div>
    </div>
    <div class="form-group row m-2">       
      <div class="col offset-md-2">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox-inline") {cb.check_box(class: "checkbox") + " " + cb.text} %>
        <% end %>
      </div>
    </div>
    <div class="form-group row m-2">       
      <div class="col-md-2 offset-md-2">
        <%= f.submit "Save article", class: "btn btn-outline-primary btn-sm mt-2" %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container p-3">
  <div class="row m-2">    
    <div class="col center">
      <h1>Edit article</h1>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container p-3">
  <div class="row m-2">
    <div class="col center">
      <h1>Articles</h1>  
    </div>
  </div>
  <div class="row justify-content-md-center">      
    <%= will_paginate %>     
  </div>
  
  <%= render 'articles', obj: @articles %>

  <div class="row justify-content-md-center">      
    <%= will_paginate %>     
  </div>
</div>

app/views/articles/new.html.erb
<div class="container p-3">
  <div class="row m-2">    
    <div class="col center">
      <h1>Create an article</h1>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container">
  <div class="row p-3">
    <div class="col center">
      <h2>Title:  <%= @article.title %></h2>
    </div>
  </div>
  
  <div class="row p-3">  
    <div class="m-2">
      Description:  <%= @article.description %>
    </div>
  </div>
  <div class="row pl-3 show_category_listing">
    <div class="ml-2">
      <% if @article.categories %>
        <p>Categories: <%= render @article.categories %></p>
      <% end %>
    </div>
  </div>
  <div class="row pl-3">
    <% if logged_in? && (current_user == @article.user || current_user.is_admin?) %>    
      <%= link_to 'Edit article', edit_article_path(@article), class: "btn btn-outline-primary btn-sm m-2" %>    
      <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger btn-sm m-2" %>
       <div class="col">            
        <div class="article-meta-details">            
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago.
                Last updated: <%= time_ago_in_words(@article.updated_at) %> ago.</small>
        </div>      
      </div>
    <% else %>
      <div class="col">            
        <div class="article-meta-details">            
          <small>Created by: <%= @article.user.username %>,  
            <%= time_ago_in_words(@article.created_at) %> ago.
                Last updated: <%= time_ago_in_words(@article.updated_at) %> ago.</small>
        </div>      
      </div>
    <% end %>
          
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge badge-pill badge-secondary m-1"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for @category do |f| %>
  <div class="container p-3">
    <div class="form-group row m-2">
      <%= f.label :name, class: "col-md-2 col-form-label" %>
        <div class="col-md">
          <%= f.text_field :name, class: "form-control", placeholder: "Category name" %>
        </div>
    </div>
    
    <div class="form-group row m-2">       
      <div class="col-md-2 offset-md-2">
        <%= f.submit class: "btn btn-outline-primary btn-sm" %>
      </div>
    </div>
  </div>  
<% end %>

app/views/categories/edit.html.erb
<div class="container p-3">
  <div class="row m-2">    
    <div class="col center">
      <h1>Edit category</h1>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="container p-3">
  <div class="row m-2">    
    <div class="col center">
      <h1>Category List</h1>
    </div>
  </div>
  <div class="row justify-content-md-center m-2">      
      <%= will_paginate %>     
  </div>
  <div class="row justify-content-md-center m-2">
    <ul class="listing">
      
      <% @categories.each do |category| %>
        <div class="row justify-content-md-center m-2">
          <div class="col center"> 
            <li>
              <h2><%= link_to  "#{category.name}", category_path(category) %></h2>      
            </li>
            <li><small><%= pluralize(category.articles.count, "article") %></small></li>
            
            <% if logged_in? && current_user.is_admin? %>
              <li><%= link_to 'Delete category', category_path(category), method: :delete,            data: {confirm: "Are you sure?"} %>
              </li>
            <% end %>
            </li>
          </div> 
        </div>  

       

      <% end %>

    </ul>
  </div>
  <div class="row justify-content-md-center">      
    <%= will_paginate %>     
  </div>
</div>

app/views/categories/new.html.erb
<div class="container p-3">
  <div class="row m-2">    
    <div class="col center">
      <h1>Create new category</h1>
    </div>
  </div>
</div>

<%= render 'shared/errors', obj: @category %>

<%= form_for @category do |f| %>
  <div class="container p-3">
    <div class="form-group row m-2">
      <%= f.label :name, class: "col-md-2 col-form-label" %>
        <div class="col-md">
          <%= f.text_field :name, class: "form-control", placeholder: "Category name" %>
        </div>
    </div>
    
    <div class="form-group row m-2">       
      <div class="col-md-2 offset-md-2">
        <%= f.submit class: "btn btn-outline-primary btn-sm" %>
      </div>
    </div>
  </div>  
<% end %>

app/views/categories/show.html.erb
<div class="container p-3">
  <div class="row m-2">    
    <div class="col center">
      <h1>Category: <%= @category.name %></h1>
      <% if logged_in? && current_user.is_admin? %>
        <span><small class="badge"><%= link_to "Edit category name", edit_category_path(@category) %></small></span>
      <% end %>
    </div>
  </div>

  

  <div class="row justify-content-md-center">      
      <%= will_paginate @category_articles %>     
  </div> 
    
  <%= render 'articles/articles', obj: @category_articles %>
  
  <div class="row justify-content-md-center">      
      <%= will_paginate @category_articles %>     
  </div>



</div>

app/views/layouts/_footer.html.erb
<div class="container">


  <footer class="footer">
    <small>

      <p>&copy Alpha Blog 2019</p>
    </small>

    <nav>
      <ul>
        <li><%= link_to 'About', about_path %></li>
      </ul>
    </nav>
  </footer>  
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="container">  
    <div class="row p-3">
      <div class="col-sm-12 m-2">
        <div class='alert alert-<%="#{name}"%>'>
          <a href="#" class="close" data-dismiss="alert">&times;</a>
          <% content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            <ul>
              <li>
                <%= msg %>
              </li>
            </ul>
        </div>
      </div>     
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light">

  <%= link_to 'Alpha Blog', root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
       <li class="nav-item">
        <%= link_to 'All Bloggers', users_path, class: "nav-link" %>      
      </li>
      <li class="nav-item">
        <%= link_to 'All articles', articles_path, class: "nav-link" %>
      </li>
      
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to 'New article', new_article_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Categories</a>
          <div class="dropdown-menu">
            <%= link_to 'All categories', categories_path, class: "dropdown-item" %>
            <% Category.all.each do |category| %>
              <%= link_to category.name, category_path(category), class: "dropdown-item" %>
            <% end %>
            
            <% if logged_in? && current_user.is_admin? %>
              <div class="dropdown-divider"></div>
              <%= link_to 'New category', new_category_path, class: "dropdown-item" %>
            <% end %>
            
            <%# <a class="dropdown-item" href="#">Something else here</a> %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Log out', logout_path, method: :delete, class: "nav-link
        " %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Your profile <%= "Admin" if current_user.is_admin? %>
          </a>
          <div class="dropdown-menu">
            <%= link_to 'View your profile', user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Edit your account', edit_user_path(current_user), class: "dropdown-item" %>
            
            <%# <a class="dropdown-item" href="#">Something else here</a> %>
          </div>
        </li>
        
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link
        " %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link
        " %>
        </li>
      <% end %>

    

     
     
    </ul>
    
    <%# <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> %>
      
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha Blog</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    

  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
        <%= yield %>
    </div>
    <%= render 'layouts/footer' %> <br>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<head>
    <meta charset="utf-8">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
     integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script> -->
    <title>Welcome to Alpha Blog Industries</title>
  </head>

<h1>All about us</h1>

<div>

  <%= link_to 'Home page', root_path, :class => "btn btn-secondary" %>


</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Welcome to Alpha Blog</title>
  </head>
  <body>
    <div class="jumbotron-fluid jumbotron">
      <div class="container">
        <h1 class="display-3">Welcome to Alpha Blog</h1>
        <div class="container center">
          <%= link_to 'Sign up now', signup_path, class: "btn btn-primary btn-xlg" %>
        </div>
      </div>
    </div>
  
  </body>
</html>

app/views/shared/_errors.html.erb
  <% if obj.errors.any? %>
    <div class="container">
      <div class="row p-3">
        <div class="col-sm-12">
          <div class= "m-2 alert alert-danger">        
            <h2>
              <%= pluralize(obj.errors.count, "error") %> prohibited this article from being                                                   saved:
            </h2>       
                
              <ul>
                <% obj.errors.full_messages.each do |msg| %>            
                <li>
                  <%= msg %>
                </li>
              <% end %>
              </ul>             
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>


<%= form_for @user do |f| %>
  <div class="container p-3">
    <div class="form-group row m-2">
      <%= f.label :username, class: "col-md-2 col-form-label" %>
        <div class="col-md">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username" %>
        </div>
    </div>
    <div class="form-group row m-2">
      <%= f.label :email, class: "col-md-2 col-form-label" %>
        <div class="col-md">
          <%= f.email_field :email,  class: "form-control", placeholder: "Enter email" %>
        </div>
    </div>
    <div class="form-group row m-2">
      <%= f.label :password, class: "col-md-2 col-form-label" %>
        <div class="col-md">
          <%= f.password_field :password,  class: "form-control", placeholder: "Enter password" %>
        </div>
    </div>
    <div class="form-group row m-2">       
      <div class="col-md-2 offset-md-2">
        <%= f.submit(@user.new_record? ? "Sign up" : "Update your account", class: "btn btn-outline-primary btn-sm") %>
      </div>
    </div>
  </div>  
<% end %>

app/views/users/edit.html.erb
<div class="container p-3">
  <div class="row m-2">    
    <div class="col center">
      <h1>Edit your account</h1>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="container p-3">
  <div class="row m-2">    
    <div class="col center">
      <h1>All users</h1>
    </div>
  </div>


  <div class="row justify-content-md-center">      
      <%= will_paginate %>     
  </div>

  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <ul class="listing center">
        <li>
          <%= link_to gravatar_for(user), user_path(user) %>      
        </li>
        <li>
          <%= link_to user.username, user_path(user) %>
        </li>
        <li>
          <small><%= pluralize(user.articles.count, "article") %></small>
        </li>
        <% if logged_in? && current_user.is_admin? %>
          <li><%= link_to 'Delete user', user_path(user), method: :delete, data: {confirm: "Are you sure?"} %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row justify-content-md-center">      
      <%= will_paginate %>     
  </div>
</div>

app/views/users/new.html.erb
<div class="container p-3">
  <div class="row m-2" >    
    <div class="col center">
      <h1>Sign up for Alpha Blog</h1>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col center">
      <h1>Welcome to <%= @user.username %>'s page</h1>  
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 offset-md-4 center">
      <%= gravatar_for @user %>
    </div>
  </div>  
    <div class="row">

      <div class="col-md-4 offset-md-4 center">
        <h4 align="center"><%= @user.username %>'s articles</h4>
      </div>  
    </div>
  <div class="row justify-content-md-center">      
      <%= will_paginate @user_articles %>     
  </div> 
    
  <%= render 'articles/articles', obj: @user_articles %>
  
  <div class="row justify-content-md-center">      
      <%= will_paginate @user_articles %>     
  </div>
  
  
</div>